### PR TITLE
Modifies display to make site scale better

### PR DESCRIPTION
**Pull request by hailed748**
The site transitions from desktop displays (27") to smaller screens like my laptop (13") pretty well, but there are still a lot errors in a mobile view.  Maybe we could discuss this further in our 1 on 1.

### CODE REVIEW

**Comment by LukeGMTravis** [comment]
I'll take a look at this after your previous PR is merged since it'll be easier to see exactly what changes are part of this PR then.

**Comment by Tetheta** [comment]
Was this ever reviewed?

**Comment by hailed748** [comment]
Somehow this got merged before it was reviewed, interesting.

**Comment by Tetheta** [comment]
Was it part of a later PR? In that case it would've been implicitly merged when that PR was

**Comment by hailed748** [comment]
I believe it was. How would I prevent something like this in the future?

**Comment by Tetheta** [comment]
The best way is to have a separate branch for every PR, and wait to submit in order if one branch pulls an older one in.

This also makes the reviews a bit easier since the diff for the later PR will be smaller (it won't include the earlier changes).

In this case the changes were reviewed in that later PR, so it's not like they weren't reviewed, it was just a larger PR than you probably intended. 

So submitting in order and only requesting review on the later PR once the previous one in the chain has merged is probably the most sure-fire way to do it.

**Comment by hailed748** [comment]
Got it. I had a PRs in order on different branches, I just requested review at the same time for all.

**Pull request merged**
